-- MySQL Script generated by MySQL Workbench
-- sáb 02 abr 2022 10:00:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema laravel_api_likeu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema laravel_api_likeu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laravel_api_likeu` DEFAULT CHARACTER SET latin1 ;
USE `laravel_api_likeu` ;

-- -----------------------------------------------------
-- Table `laravel_api_likeu`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel_api_likeu`.`users` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `laravel_api_likeu`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel_api_likeu`.`clients` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `cedula` BIGINT(20) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `user_id` BIGINT(20) UNSIGNED NOT NULL COMMENT 'Creado por Usuario',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `clients_cedula_unique` (`cedula` ASC) VISIBLE,
  INDEX `clients_user_id_foreign` (`user_id` ASC) VISIBLE,
  CONSTRAINT `clients_user_id_foreign`
    FOREIGN KEY (`user_id`)
    REFERENCES `laravel_api_likeu`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 56
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `laravel_api_likeu`.`states`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel_api_likeu`.`states` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `laravel_api_likeu`.`appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel_api_likeu`.`appointments` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `asunto` VARCHAR(255) NOT NULL,
  `fecha_hora` DATETIME NULL DEFAULT NULL,
  `state_id` BIGINT(20) UNSIGNED NOT NULL COMMENT 'Creada para Estado de Cita',
  `client_id` BIGINT(20) UNSIGNED NOT NULL COMMENT 'Creada para Cliente',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `appointments_state_id_foreign` (`state_id` ASC) VISIBLE,
  INDEX `appointments_client_id_foreign` (`client_id` ASC) VISIBLE,
  CONSTRAINT `appointments_client_id_foreign`
    FOREIGN KEY (`client_id`)
    REFERENCES `laravel_api_likeu`.`clients` (`id`),
  CONSTRAINT `appointments_state_id_foreign`
    FOREIGN KEY (`state_id`)
    REFERENCES `laravel_api_likeu`.`states` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `laravel_api_likeu`.`failed_jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel_api_likeu`.`failed_jobs` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(255) NOT NULL,
  `connection` TEXT NOT NULL,
  `queue` TEXT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `exception` LONGTEXT NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `failed_jobs_uuid_unique` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `laravel_api_likeu`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel_api_likeu`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 80
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `laravel_api_likeu`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laravel_api_likeu`.`password_resets` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `password_resets_email_index` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
